version: '3.1'

services:


  postgres:
        restart: always
        image: postgres
        container_name: "dev-postgres"
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: me
            POSTGRES_PASSWORD: 1234
            POSTGRES_DB: testDB
        volumes:
            - ./pgvol:/var/lib/postgresql/data

  pgAdmin:
      restart: always
      image: dpage/pgadmin4
      container_name: "dev-pgadmin"
      ports:
        - 8000:80
      environment:
        PGADMIN_DEFAULT_EMAIL: 1234@admin.com
        PGADMIN_DEFAULT_PASSWORD: 1234
      volumes:
        - ./pgadmin:/var/lib/pgadmin

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    container_name:   mongo-db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    container_name:   mongo-express

  airflow:
    build: ./airflow
    ports:
      - 8080:8080
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/scripts:/opt/airflow/scripts
